name: Run tests

on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [8.2]
        dependency-version:
          - prefer-stable
        os: [ubuntu-latest]

    name: PHP ${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: fileinfo, dom, curl, libxml, mbstring, bcmath, soap
          coverage: none
          tools: composer:v2

      - name: Install PHP 7 dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
        if: "matrix.php < 8"

      - name: Install PHP 8 dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress
        if: "matrix.php >= 8"

      - name: Execute tests
        run: composer test
